.github/workflows/docker-image-dev.yml, .github/workflows/docker-image.yml, .github/workflows/python-publish.yml, .github/workflows/tests.yml
Setting proper permissions for `GITHUB_TOKEN` in the workflows according to https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/.
All is needed is calling `actions/checkout`, so `contents: read` is enough, except for `docker-image.yml` which needs tagging permission, so `contens: write`.
=> Adding permissions tag for Github Actions workflows

README.md
- moved `--output` option to global space #101
- fixed links to images outside of GitHub (for example on PyPi) - CM-23013
- change git tag to stable in commit hook - CM-22157
- fix the lower Python version https://github.com/cycodehq-public/cycode-cli/pull/102#issuecomment-1520315203
=> Update README for release; CM-23013 - fix image links

cycode/cli/auth/auth_command.py, cycode/cli/code_scanner.py, cycode/cli/consts.py, cycode/cli/main.py, cycode/cli/printers/tables/sca_table_printer.py, cycode/cli/user_settings/user_settings_commands.py
=> CM-25653 - Apply text improvements

cycode/cli/code_scanner.py, cycode/cli/printers/console_printer.py, cycode/cli/printers/json_printer.py, cycode/cli/printers/printer_base.py, cycode/cli/printers/tables/table_printer_base.py, cycode/cli/printers/text_printer.py, cycode/cli/utils/progress_bar.py
this is how it looks with different output types:
no "good jobs" anymore :(
=> CM-25543 - Implement proper handling of errors in printers

poetry.lock, pyproject.toml
lock v1 to avoid issues with openssl and old Python versions (<3.9.11) on macOS
=> CM-24629 - Lock urllib3 v1

.github/workflows/black.yml, .github/workflows/build_executable.yml, .github/workflows/pre_release.yml, .github/workflows/release.yml, .github/workflows/ruff.yml, .github/workflows/tests.yml, .github/workflows/tests_full.yml
this pr also includes a fix for poetry installation. installation was broken in 1.6.0 release (yesterday, Aug 20)
=> CM-23216 - Sign Windows CLI executable

.github/workflows/build_executable.yml
=> CM-26497 - Attach signed executables and their checksums as assets to GitHub releases

README.md
@anna-aleksandrowicz pls review
=> CM-28389 - Update "cycode configure" section in README

cycode/cli/commands/auth/auth_command.py, cycode/cli/exceptions/handle_report_sbom_errors.py, cycode/cli/exceptions/handle_scan_errors.py, cycode/cli/printers/console_printer.py, cycode/cli/printers/printer_base.py
printing to stdout breaks json output which is used in our plugins
=> CM-28830 - Fix traceback printing to stderr instead of stdout

cycode/cli/commands/scan/code_scanner.py, cycode/cyclient/models.py
we need this data for our violation cards in IDE plugins
=> CM-34678 - Add Remediation Guidelines and Description to JSON output

.github/workflows/pre_release.yml, .github/workflows/release.yml, .github/workflows/ruff.yml, .github/workflows/tests.yml, .github/workflows/tests_full.yml, README.md
=> CM-35810 - Soft deprecate support for Python 3.7

.github/workflows/build_executable.yml
i ve bumped runner for x86_64 because 
> The macos-11 label has been deprecated and will no longer be available after 6/28/2024.
=> CM-35811 - Change GitHub Actions runner for building CLI for ARM macOS

cycode/cli/commands/scan/code_scanner.py, cycode/cli/commands/scan/pre_commit/pre_commit_command.py, cycode/cli/exceptions/handle_scan_errors.py, cycode/cli/files_collector/repository_documents.py, cycode/cli/files_collector/sca/sca_code_scanner.py, cycode/cli/printers/printer_base.py, cycode/cli/utils/git_proxy.py, tests/cli/exceptions/test_handle_scan_errors.py, tests/utils/test_git_proxy.py
idea: we don't need to work with git in all cases. for example, path scans could be executed without depending on git. git used to get commit history and so on.
how does it work: GitPython on import tries to find and verify git executable installed in the system. it raises an exception if it can't be found. we can catch this exception and provide a fake git provider, which will throw exceptions only on specific function calls instead of on the module import. all type hints from git module are hidden behind TYPE_CHECKING var
also, these exceptions go via our printers and depend on --output format now (json support for IDE plugins)
=> CM-30526 - Make Git executable optional

cycode/cli/commands/scan/code_scanner.py, cycode/cyclient/scan_client.py
so basically we had a lack of aggregation by `commit_id` to align with aggregation algorithm from BE service
=> CM-32255, CM-35768 - Fix scan errors during commit history scans with `--report` option

.github/workflows/pre_release.yml, .github/workflows/release.yml
they made it enabled by default week ago
release - https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.11.0
docs -  https://github.com/marketplace/actions/pypi-publish#generating-and-uploading-attestations
=> CM-41830 - Fix generating and uploading attestations to PyPI

cycode/cli/files_collector/sca/base_restore_dependencies.py, cycode/cli/files_collector/sca/go/restore_go_dependencies.py, cycode/cli/files_collector/sca/maven/restore_gradle_dependencies.py, cycode/cli/files_collector/sca/maven/restore_maven_dependencies.py, cycode/cli/files_collector/sca/npm/restore_npm_dependencies.py, cycode/cli/files_collector/sca/nuget/restore_nuget_dependencies.py, cycode/cli/files_collector/sca/sbt/restore_sbt_dependencies.py, cycode/cli/files_collector/sca/sca_code_scanner.py, cycode/cli/utils/shell_executor.py
=> CM-40909 - Add lock file restore for Golang, NPM and Nuget

.github/workflows/tests_full.yml, cycode/cli/commands/main_cli.py, cycode/cli/commands/version/version_checker.py, cycode/cli/utils/path_utils.py, tests/cli/commands/test_check_latest_version_on_close.py, tests/cli/commands/version/test_version_checker.py
DEMO:
Notes of implementation:
- It does not annoy users because it appears 1 time in a week for stable releases and 1 time in a day for pre-releases
- It always appears for `cycode version` and `cycode status` commands
- It does not appear for `--output json` to not break parsers
- It is possible to disable the version check using `cycode --no-update-notifier ...`
- It appears at the end of any stdout
=> CM-27209 - Add latest CLI version check

cycode/cli/apps/scan/code_scanner.py, cycode/cli/apps/scan/pre_commit/pre_commit_command.py, cycode/cli/apps/scan/repository/repository_command.py, cycode/cli/printers/tables/sca_table_printer.py, cycode/cli/printers/tables/table.py, cycode/cli/printers/tables/table_printer.py, tests/test_code_scanner.py
=> CM-46137 - Add visual separators of row groups; reorder columns

cycode/cli/printers/printer_base.py, cycode/cli/printers/text_printer.py, cycode/cli/utils/progress_bar.py, tests/cli/commands/test_main_command.py
Changes:
- add colorful severity
- add clickable file path
- add syntax highlight
- add a line with detection highlight when printing multi-line snippet
- remove secret SHA, scan ID, and rule ID fields from printing
- fix right label on the progress bar
- fix line numbers in the code snippet
DEMO
Before:
After:
not the final result; gonna tune it even more later (in other PRs); there is a lack of grouping/sorting etc
=> CM-45719 - Add syntax highlight for code snippets in text output

cycode/cli/app.py, cycode/cli/apps/ai_remediation/apply_fix.py, cycode/cli/apps/ai_remediation/print_remediation.py, cycode/cli/apps/auth/auth_command.py, cycode/cli/apps/auth/auth_common.py, cycode/cli/apps/auth/check_command.py, cycode/cli/apps/scan/code_scanner.py, cycode/cli/cli_types.py, cycode/cli/exceptions/handle_errors.py, cycode/cli/printers/console_printer.py, cycode/cli/printers/json_printer.py, cycode/cli/printers/printer_base.py, cycode/cli/printers/rich_printer.py, cycode/cli/printers/tables/sca_table_printer.py, cycode/cli/printers/tables/table_printer_base.py, cycode/cli/printers/text_printer.py, tests/cli/exceptions/test_handle_scan_errors.py
It supports all output types for HTML and SVG including rich (violation panels) and tables 😎 Also, it allows to show nice output in the terminal and export JSON to file at the same CLI run
=> CM-46733 - Add CLI output exporting in HTML, SVG, and JSON formats

cycode/cli/app.py, cycode/cli/apps/ai_remediation/__init__.py, cycode/cli/apps/auth/__init__.py, cycode/cli/apps/configure/__init__.py, cycode/cli/apps/ignore/__init__.py, cycode/cli/apps/report/__init__.py, cycode/cli/apps/scan/__init__.py, cycode/cli/apps/status/__init__.py, cycode/cli/cli_types.py, cycode/cli/files_collector/sca/npm/restore_npm_dependencies.py, cycode/cli/files_collector/sca/sca_code_scanner.py, cycode/cli/printers/console_printer.py, cycode/cli/printers/printer_base.py, cycode/cli/printers/rich_printer.py, cycode/cli/printers/tables/sca_table_printer.py, cycode/cli/printers/tables/table_printer.py, cycode/cli/printers/tables/table_printer_base.py, cycode/cli/printers/text_printer.py, cycode/cli/printers/utils/code_snippet_syntax.py, cycode/cli/printers/utils/detection_data.py, cycode/cli/printers/utils/detection_ordering/common_ordering.py
Changes:
- Behave for no command as for -h instead of error
- Fix colors of dark blue in Try 'cycode -h' for help.
- Add a summary at the end of violations; counter + group by severity
- Remove grouping by file path; apply global sort by severity. Where to place the full file path?
- Add violation cards for SCA as well
- double exclamation mark for critical; red circle for high
- Add clickable "In file" for every scan type
- Add description of violations to all violation cards
- Remove Cycode Guidelines from violations card (we will add it later)
- Add missing fields from IDE plugins
- Add CWE to the title of the violation card
- Improve text output
- Update tables preview for SCA
- Fix bugs with ConsolePrinter about dynamic ctx values
- Fix duplication of SCA related files in ZIP archive
=> CM-47493 - Make changes in CLI v3.0.0 after feedback

.pre-commit-hooks.yaml, README.md, cycode/cli/apps/scan/code_scanner.py, cycode/cli/apps/scan/pre_commit/pre_commit_command.py, cycode/cli/apps/scan/repository/repository_command.py, cycode/cli/cli_types.py, cycode/cli/files_collector/repository_documents.py, cycode/cli/files_collector/sca/sca_code_scanner.py, cycode/cli/printers/console_printer.py, cycode/cli/printers/rich_printer.py, cycode/cli/printers/text_printer.py, cycode/cli/printers/utils/detection_data.py, cycode/cyclient/models.py
also fixes ignore; adds text output for SCA
DEMO:
=> CM-48075 - Update pre-commit hook to work with compact output

cycode/cli/app.py
Context: https://github.com/Homebrew/homebrew-core/pull/223454
Implementation of `generate_completions_from_executable`:  https://github.com/Homebrew/brew/blob/e4e75f547480accf95acff5aa954ad8855716df0/Library/Homebrew/formula.rb#L2117-L2167
So to be able to do work around using `generate_completions_from_executable(bin/"cycode", "--show-completion", shells: [:fish, :zsh])` we need to take the first argument as shell and not rely on `shellingham`
=> CM-48457 - Fix Homebrew completions

Dockerfile, cycode/cli/files_collector/commit_range_documents.py, cycode/cli/user_settings/configuration_manager.py, cycode/cli/utils/yaml_utils.py, poetry.lock
also bumps mcp dep and fixes config related issues
=> CM-50645 - Fix secrets commit history scan

cycode/cli/files_collector/sca/maven/restore_gradle_dependencies.py, cycode/cli/files_collector/sca/sca_file_collector.py
* Added support for CLI to have customized timeout for building dependency trees, by trying to take environment value of `CYCODE_BUILD_DEP_TREE_TIMEOUT_SECONDS` and in case not set keep the default 180 seconds
=> CM-51659 - Add customization of timeouts for dependency trees (SCA restore)

cycode/cli/apps/scan/remote_url_resolver.py, cycode/cli/apps/scan/scan_parameters.py
fyi plastic cli searching in parent dirs by default
=> CM-51974 - Fix Git remote url resolving by searching in parent dirs; fix handling of multiplied paths to scan

poetry.lock, pyproject.toml
Reverts cycodehq/cycode-cli#344
Seems this causes isssues with signing for macos back out untill we get it working
=> Revert "Bump pyinstaller from 5.13.2 to 6.0.0"
